name: Build

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild .\PhysicsGame.sln /p:Configuration=Release /p:Platform=win32

      - name: Create artifact directory
        run:  mkdir artifact

      - name: Copy artifacts
        run: copy ./Build/PhysicsGame/Release/Win32/PhysicsGame.exe ./artifact

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ./artifact
          name: Physics artifact
          
  release:
      needs: build
      runs-on: ubuntu-latest
      permissions: write-all

      steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        with:
          title: New relase

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with: 
          name: PhysicsGame-artifact
          path:  ./artifact/
      
      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: zip
          GHR_PATH: ./artifact/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
