name: Build

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild .\PhysicsGame.sln /p:Configuration=Release

      - name: Create artifact directory
        run:  mkdir artifact

      - name: Copy artifacts
        run: copy ./Build/PhysicsGame/Release/Win32/PhysicsGame.exe ./artifact

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ./artifact
          name: Physics artifact
